name = "deepai-proxy"
main = "worker.js"  # 👈 Yeh batata hai entry file ka name
compatibility_date = "2025-08-02"

# 🧠 No account_id needed for new `workers.dev` style (unless binding to domain)
workers_dev = true
